### ISSUE TITLE
 bundling failed: Error: While trying to resolve module `react-native-material-dropdown

### ISSUE THREAD

**Issue by irohitb** [n4kz/react-native-material-dropdown#132]
**error:** bundling failed: Error: While trying to resolve module `react-native-material-dropdown` from file `/Users/anilbhatia/Desktop/Crypto-Main/Crypto-frontend/src/container/CoinCap.js`, the package `/Users/anilbhatia/Desktop/Crypto-Main/Crypto-frontend/node_modules/react-native-material-dropdown/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/anilbhatia/Desktop/Crypto-Main/Crypto-frontend/node_modules/react-native-material-dropdown/index.js`. Indeed, none of these files exist:

  * `/Users/anilbhatia/Desktop/Crypto-Main/Crypto-frontend/node_modules/react-native-material-dropdown/index.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/anilbhatia/Desktop/Crypto-Main/Crypto-frontend/node_modules/react-native-material-dropdown/index.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (/Users/anilbhatia/Desktop/Crypto-Main/Crypto-frontend/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:15)
    at DependencyGraph.resolveDependency (/Users/anilbhatia/Desktop/Crypto-Main/Crypto-frontend/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
    at Object.resolve (/Users/anilbhatia/Desktop/Crypto-Main/Crypto-frontend/node_modules/metro/src/lib/transformHelpers.js:116:25)
    at dependencies.map.result (/Users/anilbhatia/Desktop/Crypto-Main/Crypto-frontend/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/anilbhatia/Desktop/Crypto-Main/Crypto-frontend/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
    at /Users/anilbhatia/Desktop/Crypto-Main/Crypto-frontend/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (/Users/anilbhatia/Desktop/Crypto-Main/Crypto-frontend/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)
    at /Users/anilbhatia/Desktop/Crypto-Main/Crypto-frontend/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:467

How did error occurred? 

```
npm i react-native-modal-dropdown -save
import ModalDropdown from 'react-native-modal-dropdown'; 
```

**React Native Info**
    System:
      OS: macOS High Sierra 10.13.4
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 29.65 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by franck-nadeau** [comment]
Hey,

I think you are using the wrong module.

try the following:

```
npm i react-native-material-dropdown
import { Dropdown } from "react-native-material-dropdown";
```

Other wise you may want to ask your question on [react-native-modal-dropdown](https://github.com/sohobloo/react-native-modal-dropdown) (which isn't this site :) ).
