### ISSUE TITLE
react-native-material-dropdown not working on expo 4.4.4

### ISSUE THREAD

**Issue by sujayun** [n4kz/react-native-material-dropdown#270]
I am using react native and expo 4.4.4 and
"react-native-material-dropdown": "^0.11.1",

Just copy pasted the example usage code you have given...

Its showing below error  : 
`TypeError: undefined is not an object (evaluating '_reactNative.Animated.Text.propTypes.style')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue`

**Comment by ashiqcvcv** [comment]
I too face this issue
